version: "3.8"

services:
  ski-aggregator:
    build: .
    environment:
      environment:
      - PORT=${PORT}
      - DB_PATH=${DB_PATH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - cache
      
  cache:
    image: redis:7-alpine
    restart: unless-stopped
